require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})',
  __dir__]).strip

ENV['RCT_NEW_ARCH_ENABLED'] = '1'
platform :ios, '15.1'
prepare_react_native_project!
use_frameworks! :linkage => :static

target 'HelloWorld' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build|
        build.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
    # Edit CocoaPods' own project object. Reopening/saving another object here
    # is overwritten when CocoaPods later persists its cached project.
    project = installer.aggregate_targets.find { |target| target.user_project.path.basename.to_s == 'HelloWorld.xcodeproj' }.user_project
    app = project.targets.find { |target| target.name == 'HelloWorld' }
    group = project.main_group.find_subpath('HelloWorld', false)
    file = group.files.find { |item| File.basename(item.path) == 'SwiftRuntime.swift' } || group.new_file('HelloWorld/SwiftRuntime.swift')
    file.path = 'HelloWorld/SwiftRuntime.swift'
    app.source_build_phase.add_file_reference(file) unless app.source_build_phase.files_references.include?(file)
    app.build_configurations.each do |build|
      build.build_settings['SWIFT_VERSION'] = '6.0'
      build.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
    end
    project.save
  end
end
