# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] = '1'
$RNFirebaseDisableSPM = true
$RNFirebaseAsStaticFramework = true
use_frameworks! :linkage => :static

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'LatchwayChat' do
  if ENV['LATCHWAY_SHARED_NATIVE_SOURCE'] == '1'
    pod 'Latchway/AppAttest', :path => '../../../../latchway-ios-sdk'
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build|
        build.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
        # Xcode 27 diagnoses fmt 11's consteval paths under C++20.
        build.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17' if target.name == 'fmt'
      end
    end
    if ENV['LATCHWAY_SHARED_NATIVE_SOURCE'] == '1'
      installer.aggregate_targets.map(&:user_project).uniq.each do |project|
        project.native_targets.each do |target|
          target.build_configurations.each do |build|
            build.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) LATCHWAY_SHARED_NATIVE'
          end
        end
        project.save
      end
    end
  end
end
